---
- name: gather facts zos
  hosts: zos
  gather_facts: false
  environment: "{{ environment_vars }}"

  tasks:
    - name: Return z/OS facts in the subsets ('ipl' and 'sys') and filter out all facts that do not match 'parmlib'
      ibm.ibm_zos_core.zos_gather_facts:
        gather_subset: 
         - ipl
         - sys
        filter: 'parmlib'
      register: results

    - name: Print return info from previous tasks
      ansible.builtin.debug:
        var: results      

