---
- name: inline jcl
  hosts: zos
  gather_facts: false
  environment: "{{ environment_vars }}"
  collections:
    - ibm.ibm_zos_core
  
  tasks:
    - name: Write Hello World JCL to USS
      zos_copy:
        content:
          //HELOWRLD JOB CLASS=A,MSGCLASS=X,MSGLEVEL=(1,1)
          //STEP1    EXEC PGM=BPXBATCH
          //STDOUT   DD SYSOUT=*
          //STDERR   DD SYSOUT=*
          //STDPARM  DD *
          SH echo "Hello, World from z/OS!"
          /*
        dest: /u/ibmuser/hello_world.jcl
        force: true

    - name: submit Hello World Job
      zos_job_submit:
        src: /u/ibmuser/hello_world.jcl
        location: USS
        wait_time_s: 60
        return_output: true
      register: job_output

    - name: Show jobid and return code
      debug:
        msg: "job {{ job_output.jobs[0].job.id }} completed rc={{ job_output.jobs[0].ret_code.msg }}"

    - name: Show spool output
      debug:
        msg: "{{ job_output.jobs[0].ddnames | map(attribute*.'content') | list }}"

  