# Writes the JCL inline, submits it, and prints the spool output.
- name: Render
  hosts: zoslab
  gather_facts: false
  collections:
    - ibm.ibm_zos_core
  environment: "{{ environment_vars }}"
  vars:
    job_owner: IBMUSER
    hlq: GAMA06
    mlq: JCL
    llq: CNTL2
    libname: JCL
    primary_allocations: 2
    secondary_allocations: 4
    jcl_path: "{{ playbook_dir }}/tmp_jcl/submit local jcl" 
    jcl_dataset_name: "{{ job_owner }}.GAMA06.JCL.CNTL2"


  tasks:
    - name: Render JCL
      ansible.builtin.template:
        src: "{{ playbook_dir }}/JCL/submit local jcl
        dest: "{{ jcl_path }}"
      delegate_to: localhost

    - name: create dsn
      ibm.ibm_zos_core.zos_data_set:
        name: "{{ jcl_dataset_name }}"
        type: SEQ
        record_format: FB
        record_length: 80
        space_type= TRK
        primary_allocations: 5
        secondary_allocations: 2
        state: present
    




