---
- name: Hello World JCL job
  hosts: zoslab
  gather_facts: false
  collections:
    - ibm.ibm_zos_core
  environment: "{{ environment_vars }}"
  vars: 
    job_owner: IBMUSER

  tasks:
    - name: Submit local
      zos_job_submit:
        src: "{{ GAMA06.JCL.CNTL(HELOWRLD)}}"
        remote_src: true
        location: data_set
        encoding:
          from: UTF-8
          to: IBM-1047
      register: job_output
      wait_time_s: 30 

    - name: Show job ID and return code
      ansible.builtin.debug:
        msg: "Job {{ job_result.jobs[0].job_id }}"





